# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
    - repo: git@github.com:psf/black.git
      rev: 21.4b2
      hooks:
          - id: black
            language_version: python3.8
