"""external uids and model contexts

Revision ID: 784850ae4592
Revises: b62e06dbe8b8
Create Date: 2021-04-08 23:19:25.442619

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '784850ae4592'
down_revision = 'b62e06dbe8b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('external_uid', sa.BIGINT(), nullable=True))
    op.create_index(op.f('ix_account_handle'), 'account', ['handle'], unique=False)
    op.add_column('document', sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('document', sa.Column('external_uid', sa.BIGINT(), nullable=True))
    op.create_index(op.f('ix_document_external_uid'), 'document', ['external_uid'], unique=False)
    op.drop_column('document', 'site_resource')
    op.add_column('ticker', sa.Column('logo_url', sa.String(), nullable=True))
    op.add_column('ticker', sa.Column('security_type', sa.String(), nullable=True))
    op.add_column('ticker_mention', sa.Column('extra', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ticker_mention', 'extra')
    op.drop_column('ticker', 'security_type')
    op.drop_column('ticker', 'logo_url')
    op.add_column('document', sa.Column('site_resource', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_document_external_uid'), table_name='document')
    op.drop_column('document', 'external_uid')
    op.drop_column('document', 'context')
    op.drop_index(op.f('ix_account_handle'), table_name='account')
    op.drop_column('account', 'external_uid')
    # ### end Alembic commands ###
