"""extra on ticker

Revision ID: 7e03fe9970e9
Revises: 774594794790
Create Date: 2021-05-25 00:51:00.314267

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "7e03fe9970e9"
down_revision = "774594794790"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("ticker", sa.Column("extra", postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("ticker", "extra")
    # ### end Alembic commands ###
