"""updated_at

Revision ID: 803ab8a76a2a
Revises: ef42b0ec7a6e
Create Date: 2021-03-26 01:05:43.258211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '803ab8a76a2a'
down_revision = 'ef42b0ec7a6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('updated_at', sa.DateTime(), server_default=sa.text("(now() at time zone 'utc')"), nullable=True))
    op.add_column('account_mention', sa.Column('updated_at', sa.DateTime(), server_default=sa.text("(now() at time zone 'utc')"), nullable=True))
    op.add_column('document', sa.Column('updated_at', sa.DateTime(), server_default=sa.text("(now() at time zone 'utc')"), nullable=True))
    op.add_column('document_sentiment', sa.Column('updated_at', sa.DateTime(), server_default=sa.text("(now() at time zone 'utc')"), nullable=True))
    op.add_column('site', sa.Column('updated_at', sa.DateTime(), server_default=sa.text("(now() at time zone 'utc')"), nullable=True))
    op.add_column('ticker', sa.Column('updated_at', sa.DateTime(), server_default=sa.text("(now() at time zone 'utc')"), nullable=True))
    op.add_column('ticker_mention', sa.Column('updated_at', sa.DateTime(), server_default=sa.text("(now() at time zone 'utc')"), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ticker_mention', 'updated_at')
    op.drop_column('ticker', 'updated_at')
    op.drop_column('site', 'updated_at')
    op.drop_column('document_sentiment', 'updated_at')
    op.drop_column('document', 'updated_at')
    op.drop_column('account_mention', 'updated_at')
    op.drop_column('account', 'updated_at')
    # ### end Alembic commands ###
