"""relationships indexes and fixes

Revision ID: b2c8c1922a76
Revises: 8ed0dbd35b39
Create Date: 2021-03-25 21:26:46.286888

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b2c8c1922a76'
down_revision = '8ed0dbd35b39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('site_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_document_site_id'), 'document', ['site_id'], unique=False)
    op.drop_constraint('document_sentiment_id_fkey', 'document', type_='foreignkey')
    op.create_foreign_key(None, 'document', 'site', ['site_id'], ['id'])
    op.drop_column('document', 'sentiment_id')
    op.add_column('document_sentiment', sa.Column('document_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'document_sentiment', 'document', ['document_id'], ['id'])
    op.alter_column('site', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('site', 'url_domain',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint(None, 'site', ['name'])
    op.add_column('ticker', sa.Column('classification', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_unique_constraint(None, 'ticker', ['short_code'])
    op.add_column('ticker_mention', sa.Column('ticker_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_ticker_mention_document_id'), 'ticker_mention', ['document_id'], unique=False)
    op.drop_constraint('ticker_mention_user_id_fkey', 'ticker_mention', type_='foreignkey')
    op.create_foreign_key(None, 'ticker_mention', 'ticker', ['ticker_id'], ['id'])
    op.drop_column('ticker_mention', 'user_id')
    op.add_column('user', sa.Column('site_id', sa.Integer(), nullable=True))
    op.drop_constraint('user_site_fkey', 'user', type_='foreignkey')
    op.create_foreign_key(None, 'user', 'site', ['site_id'], ['id'])
    op.drop_column('user', 'site')
    op.create_index(op.f('ix_user_mention_document_id'), 'user_mention', ['document_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_mention_document_id'), table_name='user_mention')
    op.add_column('user', sa.Column('site', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.create_foreign_key('user_site_fkey', 'user', 'site', ['site'], ['id'])
    op.drop_column('user', 'site_id')
    op.add_column('ticker_mention', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'ticker_mention', type_='foreignkey')
    op.create_foreign_key('ticker_mention_user_id_fkey', 'ticker_mention', 'ticker', ['user_id'], ['id'])
    op.drop_index(op.f('ix_ticker_mention_document_id'), table_name='ticker_mention')
    op.drop_column('ticker_mention', 'ticker_id')
    op.drop_constraint(None, 'ticker', type_='unique')
    op.drop_column('ticker', 'classification')
    op.drop_constraint(None, 'site', type_='unique')
    op.alter_column('site', 'url_domain',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('site', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'document_sentiment', type_='foreignkey')
    op.drop_column('document_sentiment', 'document_id')
    op.add_column('document', sa.Column('sentiment_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'document', type_='foreignkey')
    op.create_foreign_key('document_sentiment_id_fkey', 'document', 'document_sentiment', ['sentiment_id'], ['id'])
    op.drop_index(op.f('ix_document_site_id'), table_name='document')
    op.drop_column('document', 'site_id')
    # ### end Alembic commands ###
