"""ticker index properties

Revision ID: b62e06dbe8b8
Revises: 1592a6e9f6ac
Create Date: 2021-03-30 01:38:41.384081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b62e06dbe8b8'
down_revision = '1592a6e9f6ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticker', sa.Column('long_name', sa.String(), nullable=True))
    op.add_column('ticker', sa.Column('short_name', sa.String(), nullable=True))
    op.add_column('ticker', sa.Column('symbol', sa.String(), nullable=True))
    op.drop_constraint('ticker_short_code_key', 'ticker', type_='unique')
    op.create_unique_constraint(None, 'ticker', ['symbol'])
    op.drop_column('ticker', 'short_code')
    op.drop_column('ticker', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticker', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('ticker', sa.Column('short_code', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'ticker', type_='unique')
    op.create_unique_constraint('ticker_short_code_key', 'ticker', ['short_code'])
    op.drop_column('ticker', 'symbol')
    op.drop_column('ticker', 'short_name')
    op.drop_column('ticker', 'long_name')
    # ### end Alembic commands ###
