"""relationships indexes and user rename

Revision ID: ef42b0ec7a6e
Revises: 8ed0dbd35b39
Create Date: 2021-03-26 00:59:15.491929

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ef42b0ec7a6e'
down_revision = '8ed0dbd35b39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("(now() at time zone 'utc')"), nullable=True),
    sa.Column('handle', sa.String(), nullable=True),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('account_mention',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("(now() at time zone 'utc')"), nullable=True),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_account_mention_document_id'), 'account_mention', ['document_id'], unique=False)
    op.drop_constraint('document_sentiment_id_fkey', 'document', type_='foreignkey')
    op.drop_constraint('document_user_id_fkey', 'document', type_='foreignkey')
    op.drop_column('document', 'user_id')
    op.drop_column('document', 'sentiment_id')
    op.drop_table('user_mention')
    op.drop_table('user')
    op.add_column('document', sa.Column('account_id', sa.Integer(), nullable=False))
    op.add_column('document', sa.Column('site_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_document_site_id'), 'document', ['site_id'], unique=False)
    op.create_foreign_key(None, 'document', 'site', ['site_id'], ['id'])
    op.create_foreign_key(None, 'document', 'account', ['account_id'], ['id'])
    op.add_column('document_sentiment', sa.Column('document_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'document_sentiment', 'document', ['document_id'], ['id'])
    op.alter_column('site', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('site', 'url_domain',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint(None, 'site', ['name'])
    op.add_column('ticker', sa.Column('classification', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_unique_constraint(None, 'ticker', ['short_code'])
    op.add_column('ticker_mention', sa.Column('ticker_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_ticker_mention_document_id'), 'ticker_mention', ['document_id'], unique=False)
    op.drop_constraint('ticker_mention_user_id_fkey', 'ticker_mention', type_='foreignkey')
    op.create_foreign_key(None, 'ticker_mention', 'ticker', ['ticker_id'], ['id'])
    op.drop_column('ticker_mention', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticker_mention', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'ticker_mention', type_='foreignkey')
    op.create_foreign_key('ticker_mention_user_id_fkey', 'ticker_mention', 'ticker', ['user_id'], ['id'])
    op.drop_index(op.f('ix_ticker_mention_document_id'), table_name='ticker_mention')
    op.drop_column('ticker_mention', 'ticker_id')
    op.drop_constraint(None, 'ticker', type_='unique')
    op.drop_column('ticker', 'classification')
    op.drop_constraint(None, 'site', type_='unique')
    op.alter_column('site', 'url_domain',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('site', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'document_sentiment', type_='foreignkey')
    op.drop_column('document_sentiment', 'document_id')
    op.add_column('document', sa.Column('sentiment_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('document', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'document', type_='foreignkey')
    op.drop_constraint(None, 'document', type_='foreignkey')
    op.create_foreign_key('document_user_id_fkey', 'document', 'user', ['user_id'], ['id'])
    op.create_foreign_key('document_sentiment_id_fkey', 'document', 'document_sentiment', ['sentiment_id'], ['id'])
    op.drop_index(op.f('ix_document_site_id'), table_name='document')
    op.drop_column('document', 'site_id')
    op.drop_column('document', 'account_id')
    op.create_table('user_mention',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text("timezone('utc'::text, now())"), autoincrement=False, nullable=True),
    sa.Column('document_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], name='user_mention_document_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='user_mention_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_mention_pkey')
    )
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text("timezone('utc'::text, now())"), autoincrement=False, nullable=True),
    sa.Column('handle', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('site', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['site'], ['site.id'], name='user_site_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_pkey')
    )
    op.drop_index(op.f('ix_account_mention_document_id'), table_name='account_mention')
    op.drop_table('account_mention')
    op.drop_table('account')
    # ### end Alembic commands ###
